name: CI

on:
  push:
    branches:
      - 'main'
      - 'patch/**'
      - 'minor/**'
      - 'major/**'
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'renovate/**'
  pull_request:
    branches:
      - 'main'
      - 'patch/**'
      - 'minor/**'
      - 'major/**'
      - 'feature/**'
      - 'fix/**'
      - 'hotfix/**'
      - 'renovate/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
  coverage:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true